using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using PickleCalLG.Meters;

namespace PickleCalLG.Export
{
    /// <summary>
    /// Generates an HTML calibration report from a CalibrationSession.
    /// </summary>
    public static class HtmlReportExporter
    {
        public static void Export(CalibrationSession session, string filePath)
        {
            using var writer = new StreamWriter(filePath, false, Encoding.UTF8);
            Export(session, writer);
        }

        public static void Export(CalibrationSession session, TextWriter writer)
        {
            writer.Write(GenerateHtml(session));
        }

        public static string GenerateHtml(CalibrationSession session)
        {
            var sb = new StringBuilder();
            sb.AppendLine("<!DOCTYPE html>");
            sb.AppendLine("<html lang='en'><head><meta charset='UTF-8'>");
            sb.AppendLine($"<title>PickleCal Report — {Esc(session.DisplayName)}</title>");
            sb.AppendLine("<style>");
            sb.AppendLine(Css);
            sb.AppendLine("</style></head><body>");

            // Header
            sb.AppendLine($"<h1>PickleCal Calibration Report</h1>");
            sb.AppendLine($"<div class='info'>");
            sb.AppendLine($"<p><strong>Display:</strong> {Esc(session.DisplayName)}</p>");
            sb.AppendLine($"<p><strong>Color Space:</strong> {Esc(session.TargetColorSpace.Name)}</p>");
            sb.AppendLine($"<p><strong>EOTF:</strong> {session.TargetEotf} (γ {session.TargetGamma:F1})</p>");
            sb.AppendLine($"<p><strong>Date:</strong> {session.CreatedUtc:yyyy-MM-dd HH:mm:ss} UTC</p>");
            sb.AppendLine($"</div>");

            // Summary stats
            sb.AppendLine("<h2>Summary</h2>");
            sb.AppendLine("<table class='stats'>");
            sb.AppendLine($"<tr><td>Total Points</td><td>{session.Points.Count}</td></tr>");
            sb.AppendLine($"<tr><td>Peak White (cd/m²)</td><td>{session.PeakWhiteLuminance:F2}</td></tr>");
            sb.AppendLine($"<tr><td>Black Level (cd/m²)</td><td>{session.BlackLuminance:F4}</td></tr>");
            string cr = session.ContrastRatio < 1e6 ? session.ContrastRatio.ToString("F0") : "∞";
            sb.AppendLine($"<tr><td>Contrast Ratio</td><td>{cr}:1</td></tr>");
            sb.AppendLine($"<tr><td>Avg ΔE₂₀₀₀ (All)</td><td>{session.AverageDeltaE:F2}</td></tr>");
            sb.AppendLine($"<tr><td>Avg ΔE₂₀₀₀ (Grayscale)</td><td>{session.AverageGrayscaleDeltaE:F2}</td></tr>");
            sb.AppendLine($"<tr><td>Max ΔE₂₀₀₀ (Grayscale)</td><td>{session.MaxGrayscaleDeltaE:F2}</td></tr>");
            sb.AppendLine("</table>");

            // Grayscale
            WriteSection(sb, "Grayscale", session.Grayscale);
            WriteSection(sb, "Near-Black", session.NearBlack);
            WriteSection(sb, "Near-White", session.NearWhite);
            WriteSection(sb, "Primaries", session.Primaries);
            WriteSection(sb, "Secondaries", session.Secondaries);
            WriteSection(sb, "Saturation", session.Saturations);

            sb.AppendLine("<p class='footer'>Generated by PickleCal</p>");
            sb.AppendLine("</body></html>");
            return sb.ToString();
        }

        private static void WriteSection(StringBuilder sb, string title, IEnumerable<CalibrationPoint> points)
        {
            var list = points.ToList();
            if (list.Count == 0) return;

            sb.AppendLine($"<h2>{Esc(title)}</h2>");
            sb.AppendLine("<table class='data'>");
            sb.AppendLine("<tr><th>Name</th><th>IRE</th><th>Luminance</th><th>x</th><th>y</th><th>CCT</th><th>ΔE₇₆</th><th>ΔE₉₄</th><th>ΔE₂₀₀₀</th><th>γ</th></tr>");

            foreach (var p in list)
            {
                string deClass = p.DeltaE2000 < 1 ? "good" : p.DeltaE2000 < 3 ? "ok" : "bad";
                string gamma = p.EffectiveGamma.HasValue ? p.EffectiveGamma.Value.ToString("F2") : "—";
                sb.AppendLine($"<tr>");
                sb.AppendLine($"<td>{Esc(p.Name)}</td>");
                sb.AppendLine($"<td>{p.TargetIre:F0}</td>");
                sb.AppendLine($"<td>{p.Luminance:F2}</td>");
                sb.AppendLine($"<td>{p.MeasuredXy.X:F4}</td>");
                sb.AppendLine($"<td>{p.MeasuredXy.Y:F4}</td>");
                sb.AppendLine($"<td>{p.CCT:F0}</td>");
                sb.AppendLine($"<td>{p.DeltaE76:F2}</td>");
                sb.AppendLine($"<td>{p.DeltaE94:F2}</td>");
                sb.AppendLine($"<td class='{deClass}'>{p.DeltaE2000:F2}</td>");
                sb.AppendLine($"<td>{gamma}</td>");
                sb.AppendLine("</tr>");
            }
            sb.AppendLine("</table>");

            // Category averages
            double avgDe = list.Average(p => p.DeltaE2000);
            double maxDe = list.Max(p => p.DeltaE2000);
            sb.AppendLine($"<p class='avg'>Avg ΔE₂₀₀₀: {avgDe:F2} | Max ΔE₂₀₀₀: {maxDe:F2}</p>");
        }

        private static string Esc(string s) =>
            System.Net.WebUtility.HtmlEncode(s);

        private const string Css = @"
body { font-family: 'Segoe UI', Tahoma, sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; background: #1a1a2e; color: #e0e0e0; }
h1 { color: #66bb6a; border-bottom: 2px solid #66bb6a; padding-bottom: 8px; }
h2 { color: #42a5f5; margin-top: 30px; }
.info { background: #16213e; padding: 15px; border-radius: 8px; margin: 15px 0; }
.info p { margin: 4px 0; }
table { border-collapse: collapse; width: 100%; margin: 10px 0; }
table.stats { width: auto; }
table.stats td { padding: 6px 20px 6px 0; }
table.stats td:last-child { font-weight: bold; color: #fff; }
table.data th { background: #0f3460; color: #fff; padding: 8px 12px; text-align: left; }
table.data td { padding: 6px 12px; border-bottom: 1px solid #333; }
table.data tr:nth-child(even) { background: #16213e; }
table.data tr:hover { background: #1a3a5c; }
.good { color: #66bb6a; font-weight: bold; }
.ok { color: #ffa726; font-weight: bold; }
.bad { color: #ef5350; font-weight: bold; }
.avg { color: #90caf9; font-style: italic; margin: 5px 0 20px 0; }
.footer { margin-top: 40px; color: #666; text-align: center; font-size: 12px; }
";
    }
}
